# Generated by Django 5.2.2 on 2025-07-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
